### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by ekeih** [hechi/rooftop#3]
Hi,
it would be nice if you could add a requirements file to declare the dependencies of rooftop.
Thanks!

**Comment by hechi** [comment]
you mean the python dependencies? or also a ldap explanation?

**Comment by ekeih** [comment]
Yes, I mean the python dependencies.

**Comment by hechi** [comment]
Hey @ekeih i added a requirements.txt but i am not sure if i got everything :)
